site_name: Partomatic
site_url: https://partomatic.readthedocs.io/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    - navigation.path
    - toc.integrate
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      toc_depth: 3
  - markdown_include.include:
      base_path: .
nav:
  - Overview: index.md
  - Developer’s Guide:
    - AutomatablePart: automatable_part.md
    - PartomaticConfig: partomatic_config.md
    - Partomatic: partomatic.md