[project]
name = "partomatic"
version = "0.0.1"
authors = [
  { name="x0pherl"},
]
description = "build123d Part extended for CI/CD automation"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/x0pher/partomatic"
Issues = "https://github.com/x0pher/partomatic/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"